[versions]
agp = "8.7.3"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
firebaseInappmessaging = "21.0.1"
playServicesGamesV2 = "20.1.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
firebase-inappmessaging = { group = "com.google.firebase", name = "firebase-inappmessaging", version.ref = "firebaseInappmessaging" }
play-services-games-v2-v2012 = { module = "com.google.android.gms:play-services-games-v2", version.ref = "playServicesGamesV2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

